Upkeep:
  # Want to learn how upkeep works? Check out the wiki at;
  # https://github.com/ColonelKai/RoutesByPlayers/wiki/Upkeep
  # requires vault to be installed
  Money:
    Use: false # if enabled, will disable item-based Upkeep.
    Amount: 0.5 # for every block
  Item:
    Item: diamond # the item needed for the upkeep
    Distance: 20 # amount of blocks 1 of Item will pay for.

# if the stop points coordinates will be available to everyone on GUI
PublicStopPoints: true
# if Dynmap is installed, it will add markers for StopPoints
StopPointsOnDynmap: true
# Minimum distance required between 2 StopPoints. If someone tries
# to create a StopPoint while there is another nearby, the plugin
# will not allow it.
MinimumDistance: 0
# Maximum amount of StopPoints a player can have.
MaximumStopPoints: 5

