Upkeep:
  # Want to learn how upkeep works? Check out the wiki at;
  # https://github.com/ColonelKai/RoutesByPlayers/wiki/Upkeep
    Amount: 10 # amount of blocks 1 currency will cover

Currency:
  # determines the way which your players will handle upkeep,
  # and travel costs.
  # if you should use vault money. Requires Vault, duh.
  Vault: false
  # if you aren't using vault, what item you should use.
  Item: DIAMOND

# if the nodes coordinates will be available to everyone on GUI
PublicNodes: true
# if Dynmap is installed, it will add markers for nodes
NodesOnDynmap: true
# Minimum distance required between 2 nodes. If someone tries
# to create a node while there is another within this distance, the
# plugin will not allow it.
MinimumDistance: 0
# Maximum amount of Nodes a player can have.
MaximumNodes: 5

